"""initial schema baseline

Every table, index, constraint, and enum in the application models is
emitted as explicit DDL here. This replaces the earlier
``Base.metadata.create_all`` baseline so the schema is properly
versioned and can be replayed on both SQLite (tests + local) and
PostgreSQL (CI + production). Future schema changes must be proper
incremental migrations on top of this revision.

Specific invariants this revision carries (worth calling out so they
do not silently drift):

- ``uq_rule_workflow_code`` on ``rules`` (workflow_id, code)
- ``uq_doc_req_workflow_global_type`` on ``document_requirements``
  with ``postgresql_where`` and ``sqlite_where`` for ``stage_id IS NULL``
- ``uq_doc_req_workflow_stage_type`` on ``document_requirements``
  with the same partial predicate for ``stage_id IS NOT NULL``
- Native enum types for every enum in ``app.models.enums``
- ``ix_audit_logs_org_id`` composite (organization_id, id) added in
  Phase 2 for ``_latest_hash_in_scope`` writes and ``verify_chain``
  scans

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-21
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INTAKE_COORDINATOR', 'REVIEWER', 'MANAGER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_workflow_org_slug')
    )
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflows_slug'), 'workflows', ['slug'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'order_index', name='uq_stage_workflow_order'),
    sa.UniqueConstraint('workflow_id', 'slug', name='uq_stage_workflow_slug')
    )
    op.create_index(op.f('ix_workflow_stages_workflow_id'), 'workflow_stages', ['workflow_id'], unique=False)
    op.create_table('document_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('PHOTO_ID', 'INSURANCE_CARD', 'CONSENT_FORM', 'GUARDIAN_AUTHORIZATION', 'MEDICAL_HISTORY_FORM', 'OTHER', name='document_type'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('applies_when_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requirements_stage_id'), 'document_requirements', ['stage_id'], unique=False)
    op.create_index(op.f('ix_document_requirements_workflow_id'), 'document_requirements', ['workflow_id'], unique=False)
    op.create_index('uq_doc_req_workflow_global_type', 'document_requirements', ['workflow_id', 'document_type'], unique=True, postgresql_where=sa.text('stage_id IS NULL'), sqlite_where=sa.text('stage_id IS NULL'))
    op.create_index('uq_doc_req_workflow_stage_type', 'document_requirements', ['workflow_id', 'stage_id', 'document_type'], unique=True, postgresql_where=sa.text('stage_id IS NOT NULL'), sqlite_where=sa.text('stage_id IS NOT NULL'))
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=80), nullable=True),
    sa.Column('subject_full_name', sa.String(length=200), nullable=False),
    sa.Column('subject_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'BLOCKED', 'READY', 'CLOSED', name='record_status'), nullable=False),
    sa.Column('insurance_status', sa.Enum('UNKNOWN', 'PENDING', 'VERIFIED', 'UNINSURED_ACKNOWLEDGED', 'INVALID', name='insurance_status'), nullable=False),
    sa.Column('consent_status', sa.Enum('NOT_PROVIDED', 'PARTIAL', 'SIGNED', 'EXPIRED', name='consent_status'), nullable=False),
    sa.Column('medical_history_status', sa.Enum('NOT_STARTED', 'INCOMPLETE', 'COMPLETE', name='medical_history_status'), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('guardian_authorization_signed', sa.Boolean(), nullable=False),
    sa.Column('allergy_info_provided', sa.Boolean(), nullable=False),
    sa.Column('insurance_in_network', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_band'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_assigned_user_id'), 'records', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_records_current_stage_id'), 'records', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_records_external_reference'), 'records', ['external_reference'], unique=False)
    op.create_index(op.f('ix_records_organization_id'), 'records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_records_workflow_id'), 'records', ['workflow_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('action', sa.Enum('WARN', 'BLOCK', name='rule_action_type'), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'HIGH', 'CRITICAL', name='rule_severity'), nullable=False),
    sa.Column('risk_weight', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'code', name='uq_rule_workflow_code')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=False)
    op.create_index(op.f('ix_rules_stage_id'), 'rules', ['stage_id'], unique=False)
    op.create_index(op.f('ix_rules_workflow_id'), 'rules', ['workflow_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entry_hash'), 'audit_logs', ['entry_hash'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['organization_id', 'id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PHOTO_ID', 'INSURANCE_CARD', 'CONSENT_FORM', 'GUARDIAN_AUTHORIZATION', 'MEDICAL_HISTORY_FORM', 'OTHER', name='document_type'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('storage_uri', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'VERIFIED', 'REJECTED', 'EXPIRED', name='document_status'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_record_id'), 'documents', ['record_id'], unique=False)
    op.create_table('rule_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('action_applied', sa.Enum('NONE', 'WARN', 'BLOCK', name='rule_action_applied'), nullable=False),
    sa.Column('risk_applied', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluations_record_id'), 'rule_evaluations', ['record_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_rule_id'), 'rule_evaluations', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_evaluations_rule_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_record_id'), table_name='rule_evaluations')
    op.drop_table('rule_evaluations')
    op.drop_index(op.f('ix_documents_record_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entry_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_rules_workflow_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_stage_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_records_workflow_id'), table_name='records')
    op.drop_index(op.f('ix_records_organization_id'), table_name='records')
    op.drop_index(op.f('ix_records_external_reference'), table_name='records')
    op.drop_index(op.f('ix_records_current_stage_id'), table_name='records')
    op.drop_index(op.f('ix_records_assigned_user_id'), table_name='records')
    op.drop_table('records')
    op.drop_index('uq_doc_req_workflow_stage_type', table_name='document_requirements', postgresql_where=sa.text('stage_id IS NOT NULL'), sqlite_where=sa.text('stage_id IS NOT NULL'))
    op.drop_index('uq_doc_req_workflow_global_type', table_name='document_requirements', postgresql_where=sa.text('stage_id IS NULL'), sqlite_where=sa.text('stage_id IS NULL'))
    op.drop_index(op.f('ix_document_requirements_workflow_id'), table_name='document_requirements')
    op.drop_index(op.f('ix_document_requirements_stage_id'), table_name='document_requirements')
    op.drop_table('document_requirements')
    op.drop_index(op.f('ix_workflow_stages_workflow_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_workflows_slug'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Postgres keeps enum types around after the tables that reference
    # them are dropped. Without explicit cleanup, a subsequent
    # `alembic upgrade head` fails with "type already exists" because
    # SQLAlchemy will try to CREATE TYPE on the next upgrade. SQLite
    # has no notion of user-defined types, so this block is a no-op
    # for the default test dialect.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "user_role",
            "record_status",
            "insurance_status",
            "consent_status",
            "medical_history_status",
            "risk_band",
            "document_type",
            "document_status",
            "rule_action_type",
            "rule_severity",
            "rule_action_applied",
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
